name = "formalization"
version = "0.2.0"
defaultTargets = ["MathlibUpstream", "Formalization"]

[lean_options]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[require]]
name = "«spectral-positivity-ext»"
path = "spectral-positivity-ext"

[[lean_lib]]
name = "MathlibUpstream"

[[lean_lib]]
name = "Formalization"