import sys

def divisor_sum_11(n):
    return sum(d**11 for d in range(1, n + 1) if n % d == 0)

def compute_tau_up_to(max_n):
    # tau(n) is the coefficient of q^n in q * prod_{k=1}^{max_n} (1 - q^k)^24
    # We can compute this iteratively.
    coeffs = [0] * (max_n + 1)
    coeffs[0] = 1
    
    for k in range(1, max_n + 1):
        new_coeffs = list(coeffs)
        for _ in range(24):
            temp = list(new_coeffs)
            for i in range(k, max_n + 1):
                temp[i] -= new_coeffs[i - k]
            new_coeffs = temp
        coeffs = new_coeffs
        
    # Multiply by q means shifting right by 1
    tau = [0] * (max_n + 1)
    for i in range(1, max_n + 1):
        tau[i] = coeffs[i - 1]
        
    return tau

def main():
    max_n = 50
    tau_vals = compute_tau_up_to(max_n)
    
    print("-- Generated by tau_codegen.py")
    print("import Formalization.RamanujanTau\n")
    print("set_option maxRecDepth 2000000")
    print("set_option maxHeartbeats 0\n")
    
    for n in range(1, max_n + 1):
        tau_n = tau_vals[n]
        sigma11_n = divisor_sum_11(n)
        
        # Verify congruence in Python
        assert (tau_n - sigma11_n) % 691 == 0
        
        print(f"theorem ramanujan_congruence_finite_{n} : ramanujan_congruence_comp {n} = true := by decide")

if __name__ == "__main__":
    main()
