import Mathlib.Data.ZMod.Basic
import Mathlib.RingTheory.RootsOfUnity.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Tactic
import Formalization.Dynamics.SpectralCircle

/-!
# Schreier Dynamical Trace and Monomial Fixed Point Formulas

This module formalizes:
1. The Schreier affine action on `ZMod (2^n)` generated by the directed Collatz transitions
   `x ↦ 3x` and `x ↦ 3x - 1`.
2. The monomial representation of the directed Collatz operator `D_n` in the Fourier basis.
3. The exact fixed point trace formula `directed_trace_eq_fixed_point_sum` for powers `D_n^m`.
4. The vanishing theorem `directed_trace_odd_vanishes` for odd residue trace contributions
   at all intermediate powers `0 < m < 2^{n-2}` when `n ≥ 3`.
5. The full cycle return trace formula at `m = 2^{n-2}`.
-/

open scoped BigOperators

set_option linter.deprecated false

namespace SchreierDynamicalTrace

-- ============================================================================
-- 1. SCHREIER AFFINE ACTION
-- ============================================================================

/-- Generator 0 of the directed Schreier action: `x ↦ 3x`. -/
def schreierGen0 (n : ℕ) (x : ZMod (2^n)) : ZMod (2^n) :=
  3 * x

/-- Generator 1 of the directed Schreier action: `x ↦ 3x - 1`. -/
def schreierGen1 (n : ℕ) (x : ZMod (2^n)) : ZMod (2^n) :=
  3 * x - 1

/-- Step transition for generator bit `b : Bool`: `false ↦ 3x`, `true ↦ 3x - 1`. -/
def schreierStep (n : ℕ) (b : Bool) (x : ZMod (2^n)) : ZMod (2^n) :=
  if b then 3 * x - 1 else 3 * x

@[simp]
lemma schreierStep_false (n : ℕ) (x : ZMod (2^n)) : schreierStep n false x = 3 * x := rfl

@[simp]
lemma schreierStep_true (n : ℕ) (x : ZMod (2^n)) : schreierStep n true x = 3 * x - 1 := rfl

/-- Action of a binary word `w : List Bool` under the Schreier affine dynamical system. -/
def schreierWordApply (n : ℕ) : List Bool → ZMod (2^n) → ZMod (2^n)
  | [], x => x
  | b :: bs, x => schreierWordApply n bs (schreierStep n b x)

@[simp]
lemma schreierWordApply_nil (n : ℕ) (x : ZMod (2^n)) : schreierWordApply n [] x = x := rfl

@[simp]
lemma schreierWordApply_cons (n : ℕ) (b : Bool) (bs : List Bool) (x : ZMod (2^n)) :
    schreierWordApply n (b :: bs) x = schreierWordApply n bs (schreierStep n b x) := rfl

lemma schreierWordApply_append (n : ℕ) (w1 w2 : List Bool) (x : ZMod (2^n)) :
    schreierWordApply n (w1 ++ w2) x = schreierWordApply n w2 (schreierWordApply n w1 x) := by
  induction w1 generalizing x with
  | nil => rfl
  | cons b bs ih => exact ih (schreierStep n b x)

lemma schreierWordApply_replicate_false (n : ℕ) (m : ℕ) (x : ZMod (2^n)) :
    schreierWordApply n (List.replicate m false) x = (3 : ZMod (2^n))^m * x := by
  induction m generalizing x with
  | zero => simp
  | succ m ih =>
    simp only [List.replicate_succ, schreierWordApply_cons, schreierStep_false, ih (3 * x), pow_succ']
    ring

-- ============================================================================
-- 2. FOURIER BASIS AND MONOMIAL WEIGHT FORMULAS
-- ============================================================================

variable {F : Type*} [Field F]

/-- The Fourier additive character `χ_k(x) = ζ^(k * x).val` for primitive root `ζ`. -/
def chi {n : ℕ} (zeta : F) (k x : ZMod (2^n)) : F :=
  zeta ^ (k * x).val

/-- Single-step monomial weight `w_1(k) = 1 + ζ^(-k).val`. -/
def monomialWeightStep {n : ℕ} (zeta : F) (k : ZMod (2^n)) : F :=
  1 + zeta ^ (-k).val

/-- Multi-step monomial weight along the `×3` orbit of length `m`:
    `W_m(k) = ∏_{j=0}^{m-1} (1 + ζ^(-3^j k).val)`. -/
def monomialWeight {n : ℕ} (zeta : F) (k : ZMod (2^n)) (m : ℕ) : F :=
  ∏ j ∈ Finset.range m, (1 + zeta ^ (-((3 : ZMod (2^n))^j * k)).val)

@[simp]
lemma monomialWeight_zero {n : ℕ} (zeta : F) (k : ZMod (2^n)) :
    monomialWeight zeta k 0 = 1 :=
  Finset.prod_range_zero _

lemma monomialWeight_one {n : ℕ} (zeta : F) (k : ZMod (2^n)) :
    monomialWeight zeta k 1 = 1 + zeta ^ (-k).val := by
  simp [monomialWeight]

lemma monomialWeight_succ {n : ℕ} (zeta : F) (k : ZMod (2^n)) (m : ℕ) :
    monomialWeight zeta k (m + 1) =
    monomialWeight zeta k m * (1 + zeta ^ (-((3 : ZMod (2^n))^m * k)).val) :=
  Finset.prod_range_succ _ _

lemma monomialWeight_succ' {n : ℕ} (zeta : F) (k : ZMod (2^n)) (m : ℕ) :
    monomialWeight zeta k (m + 1) =
    (1 + zeta ^ (-k).val) * monomialWeight zeta (3 * k) m := by
  dsimp [monomialWeight]
  rw [Finset.prod_range_succ', mul_comm]
  congr 1
  · simp
  · apply Finset.prod_congr rfl
    intro j _
    have hj : -((3 : ZMod (2^n))^(j + 1) * k) = -((3 : ZMod (2^n))^j * (3 * k)) := by
      rw [pow_succ]; ring
    rw [hj]

-- ============================================================================
-- 3. MONOMIAL MATRIX AND TRACE FORMULAS
-- ============================================================================

/-- The monomial matrix representation of the $m$-th power directed operator in Fourier space.
    The entry `(i, j)` is `W_m(i)` if `j = 3^m * i`, and `0` otherwise. -/
def monomialMatrix (n : ℕ) (zeta : F) (m : ℕ) : Matrix (ZMod (2^n)) (ZMod (2^n)) F :=
  fun i j => if j = (3 : ZMod (2^n))^m * i then monomialWeight zeta i m else 0

@[simp]
lemma monomialMatrix_apply (n : ℕ) (zeta : F) (m : ℕ) (i j : ZMod (2^n)) :
    monomialMatrix n zeta m i j =
    if j = (3 : ZMod (2^n))^m * i then monomialWeight zeta i m else 0 :=
  rfl

/-- The fixed point trace sum of the $m$-th power directed Collatz operator. -/
def fixedPointTrace (n : ℕ) (zeta : F) (m : ℕ) : F :=
  ∑ k : ZMod (2^n), if (3 : ZMod (2^n))^m * k = k then monomialWeight zeta k m else 0

/-- **Exact Monomial Fixed Point Trace Formula**:
    The matrix trace of `monomialMatrix n zeta m` equals the sum over all fixed points of `x ↦ 3^m x`
    weighted by the orbit monomial factor `W_m(k)`. -/
theorem directed_trace_eq_fixed_point_sum {F : Type*} [Field F] (n : ℕ) (_hn : n ≥ 1)
    (zeta : F) (_hzeta : IsPrimitiveRoot zeta (2^n)) (m : ℕ) :
    Matrix.trace (monomialMatrix n zeta m) = fixedPointTrace n zeta m := by
  simp only [Matrix.trace, Matrix.diag, monomialMatrix_apply, fixedPointTrace]
  apply Finset.sum_congr rfl
  intro k _
  by_cases h : (3 : ZMod (2^n))^m * k = k
  · rw [if_pos h, if_pos h.symm]
  · rw [if_neg h, if_neg (fun h' => h h'.symm)]

/-- Equivalent filter-sum expression for the fixed point trace. -/
lemma fixedPointTrace_eq_filter_sum (n : ℕ) (zeta : F) (m : ℕ) :
    fixedPointTrace n zeta m =
    ∑ k ∈ Finset.univ.filter (fun k : ZMod (2^n) => (3 : ZMod (2^n))^m * k = k), monomialWeight zeta k m := by
  simp only [fixedPointTrace, ← Finset.sum_filter]

-- ============================================================================
-- 4. ODD RESIDUE TRACE CONTRIBUTION AND VANISHING THEOREM
-- ============================================================================

/-- The Finset of odd residues in `ZMod (2^n)`. -/
def oddResidues (n : ℕ) : Finset (ZMod (2^n)) :=
  {x : ZMod (2^n) | Odd x.val}.toFinset

/-- The trace contribution of the odd character sector. -/
def oddFixedPointTrace (n : ℕ) (zeta : F) (m : ℕ) : F :=
  ∑ k ∈ oddResidues n, if (3 : ZMod (2^n))^m * k = k then monomialWeight zeta k m else 0

/-- Multiplication by $3^m$ on odd residues has no fixed points for $0 < m < 2^{n-2}$ ($n \ge 3$). -/
lemma three_pow_mul_odd_ne_self (n : ℕ) (hn : n ≥ 3) (m : ℕ)
    (hm_pos : 0 < m) (hm_lt : m < 2^(n-2)) (k : ZMod (2^n)) (hk : Odd k.val) :
    (3 : ZMod (2^n))^m * k ≠ k := by
  intro h_fix
  have hk_unit : IsUnit k := (odd_iff_isUnit (by omega) k).mp hk
  have h_pow_one : (3 : ZMod (2^n))^m = 1 :=
    IsUnit.mul_right_cancel hk_unit (by simpa using h_fix)
  let u_3 : (ZMod (2^n))ˣ := ZMod.unitOfCoprime 3 (Nat.Coprime.pow_right n (by decide))
  have hu3_m_eq_one : u_3^m = 1 := Units.ext (by push_cast; exact h_pow_one)
  have h_dvd : orderOf u_3 ∣ m := orderOf_dvd_of_pow_eq_one hu3_m_eq_one
  rw [order_three_mod_pow_two n hn] at h_dvd
  have := Nat.le_of_dvd hm_pos h_dvd
  omega

/-- **Vanishing Theorem for Odd Directed Trace**:
    For $n \ge 3$ and all intermediate powers $0 < m < 2^{n-2}$,
    the fixed point trace contribution from all odd residues vanishes identically. -/
theorem directed_trace_odd_vanishes (n : ℕ) (hn : n ≥ 3) (zeta : F) (m : ℕ)
    (hm_pos : 0 < m) (hm_lt : m < 2^(n-2)) :
    oddFixedPointTrace n zeta m = 0 := by
  simp only [oddFixedPointTrace]
  refine Finset.sum_eq_zero (fun k hk => ?_)
  rw [oddResidues, Set.mem_toFinset] at hk
  simp [three_pow_mul_odd_ne_self n hn m hm_pos hm_lt k hk]

-- ============================================================================
-- 5. FULL CYCLE RETURN TRACE FORMULA (m = 2^{n-2})
-- ============================================================================

/-- At the full cycle length $m = 2^{n-2}$, $3^m k = k$ holds for all $k \in \mathbb{Z}/2^n\mathbb{Z}$. -/
lemma three_pow_full_cycle_mul (n : ℕ) (hn : n ≥ 3) (k : ZMod (2^n)) :
    (3 : ZMod (2^n))^(2^(n-2)) * k = k := by
  rw [three_pow_two_pow_mod_pow_two n hn, one_mul]

/-- At the full cycle return $m = 2^{n-2}$, every odd residue contributes its full orbit weight
    to the trace, with no vanishing indicator. -/
theorem directed_trace_full_cycle_odd (n : ℕ) (hn : n ≥ 3) (zeta : F) :
    oddFixedPointTrace n zeta (2^(n-2)) =
    ∑ k ∈ oddResidues n, monomialWeight zeta k (2^(n-2)) := by
  simp only [oddFixedPointTrace]
  apply Finset.sum_congr rfl
  intro k _
  simp only [three_pow_full_cycle_mul n hn k, ↓reduceIte]

/-- Total fixed point trace at full cycle return $m = 2^{n-2}$ simplifies to the unconditioned
    sum of monomial weights across all residues. -/
theorem directed_trace_full_cycle_total (n : ℕ) (hn : n ≥ 3) (zeta : F) :
    fixedPointTrace n zeta (2^(n-2)) =
    ∑ k : ZMod (2^n), monomialWeight zeta k (2^(n-2)) := by
  simp only [fixedPointTrace]
  apply Finset.sum_congr rfl
  intro k _
  simp only [three_pow_full_cycle_mul n hn k, ↓reduceIte]

/-- The total fixed point trace splits into the sum of odd residues and even residues. -/
theorem fixedPointTrace_eq_odd_add_even (n : ℕ) (_hn : n ≥ 1) (zeta : F) (m : ℕ) :
    fixedPointTrace n zeta m =
    oddFixedPointTrace n zeta m +
    ∑ k ∈ {x : ZMod (2^n) | Even x.val}.toFinset,
      if (3 : ZMod (2^n))^m * k = k then monomialWeight zeta k m else 0 := by
  dsimp [fixedPointTrace, oddFixedPointTrace, oddResidues]
  have h_univ : (Finset.univ : Finset (ZMod (2^n))) =
      {x : ZMod (2^n) | Odd x.val}.toFinset ∪ {x : ZMod (2^n) | Even x.val}.toFinset := by
    ext x
    simp only [Finset.mem_univ, Finset.mem_union, Set.mem_toFinset, Set.mem_ofPred_eq, true_iff]
    exact (Nat.even_or_odd x.val).symm
  have h_disj : Disjoint {x : ZMod (2^n) | Odd x.val}.toFinset
      {x : ZMod (2^n) | Even x.val}.toFinset := by
    rw [Finset.disjoint_iff_ne]
    intro a ha b hb hab
    rw [Set.mem_toFinset, Set.mem_ofPred_eq] at ha hb
    subst hab
    exact Nat.not_even_iff_odd.mpr ha hb
  conv_lhs => rw [h_univ]
  rw [Finset.sum_union h_disj]

end SchreierDynamicalTrace
