import json
import math
import numpy as np
import mpmath
import sympy as sp

mpmath.mp.dps = 35

# Load complex ap from step 1334
filepath = r"C:\Users\x\.gemini\antigravity\brain\f1ebe7a5-1121-4865-9a68-9e435b87c778\.system_generated\steps\1334\content.md"
with open(filepath, "r", encoding="utf-8") as f:
    text = f.read()
json_text = text.split("---")[1].strip()
data_hecke = json.loads(json_text)
entry = data_hecke["data"][0]
ap_raw = entry["ap"]
N = 800

# Base field generator
zeta20 = np.exp(2j * np.pi / 20.0)

def parse_coeff(terms):
    if not terms: return 0.0 + 0.0j
    return sum(c * (zeta20 ** k) for c, k in terms)

primes_list = list(sp.primerange(2, 2001))
a_p_complex = {}
for idx, p in enumerate(primes_list):
    if idx < len(ap_raw):
        a_p_complex[p] = parse_coeff(ap_raw[idx])

# Build character chi
lut_32 = {}
for x1 in [0, 1]:
    for x2 in range(8):
        lut_32[((-1)**x1 * 5**x2) % 32] = (x1, x2)
lut_25 = {}
for x3 in range(20):
    lut_25[(2**x3) % 25] = x3

def chi(n):
    n = int(n)
    if math.gcd(n, 800) > 1: return 0.0 + 0.0j
    x1, _ = lut_32[n % 32]
    x3 = lut_25[n % 25]
    val = (5*x1 + 4*x3) % 10
    return np.exp(2j * np.pi * val / 10)

# Galois automorphisms of Q(zeta_20)
# Gal(Q(zeta_20)/Q) = (Z/20Z)* = {1, 3, 9, 7, 11, 13, 19, 17}
# The automorphisms that stabilize the coefficient field K = Q(zeta_12) (which is Q(sqrt(-3)))
# are generated by sigma_3: zeta_20 -> zeta_20^3.
# The 4 conjugates are generated by powers of sigma_3: m in {1, 3, 9, 7}.
gal_m = [1, 3, 9, 7]

def get_galois_conjugate_coeffs(j, M=1500):
    """
    Get Dirichlet coefficients a_n for the j-th Galois conjugate form f^(j).
    j = 0, 1, 2, 3 corresponds to m = gal_m[j] = 1, 3, 9, 7.
    """
    m = gal_m[j]
    
    # Conjugate prime traces
    # The raw Hecke eigenvalue for prime p is a sum of c * zeta_20^k.
    # The Galois action maps this to sum of c * zeta_20^(m*k).
    a_p_conj = {}
    for p in primes_list:
        if p in a_p_complex:
            # Recompute with conjugated zeta
            terms = ap_raw[primes_list.index(p)]
            if not terms:
                a_p_conj[p] = 0.0 + 0.0j
            else:
                a_p_conj[p] = sum(c * (zeta20 ** ((m * k) % 20)) for c, k in terms)
        else:
            a_p_conj[p] = 0.0 + 0.0j

    # Conjugate character
    # The character chi is a homomorphism to roots of unity.
    # The Galois action m acts on chi(p).
    # Since chi(p) has order 10, it is in Q(zeta_20), so chi^(j)(p) = chi(p)^m.
    def chi_conj(n):
        c_val = chi(n)
        if abs(c_val) < 1e-10:
            return 0.0 + 0.0j
        # Find power of zeta_10
        angle = np.angle(c_val) / (2.0 * np.pi)
        k = int(round(angle * 10)) % 10
        return np.exp(2j * np.pi * ((k * m) % 10) / 10)

    # Build a_n up to M
    a = np.zeros(M+1, dtype=complex)
    a[1] = 1.0
    primes_subset = [p for p in primes_list if p <= M]
    
    for p in primes_subset:
        ap = a_p_conj.get(p, 0.0+0j)
        chip = chi_conj(p)
        pk_coeffs = [1.0+0j, ap]
        k = 2
        while p**k <= M:
            pk_coeffs.append(ap * pk_coeffs[k-1] - chip * pk_coeffs[k-2])
            k += 1
        for k in range(1, len(pk_coeffs)):
            if p**k <= M:
                a[p**k] = pk_coeffs[k]

    for i in range(2, M+1):
        if abs(a[i]) < 1e-14:
            continue
        for p in primes_subset:
            if i * p > M:
                break
            if math.gcd(i, p) > 1:
                continue
            ap = a_p_conj.get(p, 0.0+0j)
            chip = chi_conj(p)
            pk_coeffs = [1.0+0j, ap]
            kk = 2
            while i * p**kk <= M:
                pk_coeffs.append(ap * pk_coeffs[kk-1] - chip * pk_coeffs[kk-2])
                kk += 1
            for k in range(1, len(pk_coeffs)):
                pk = p**k
                if i * pk > M:
                    break
                a[i*pk] = a[i] * pk_coeffs[k]
                
    return a

# Precompute a_n for all 4 conjugate forms
print("Precomputing Dirichlet coefficients for the 4 conjugate forms...")
a_conjs = [get_galois_conjugate_coeffs(j) for j in range(4)]
print("Done.")

# Fast AFE evaluator
M_sum = 1200
log_n = np.log(np.arange(1, M_sum+1))

def compute_S1_S2_P(t, j):
    """Compute S1, S2, and P for conjugate form j at t."""
    a_arr = a_conjs[j][1:] # 1..M
    s = 0.5 + 1j*t
    
    # S1
    powers = np.exp(-s * log_n[:M_sum])
    S1 = np.dot(a_arr[:M_sum], powers)
    
    # S2
    s2 = 0.5 - 1j*t
    powers2 = np.exp(-s2 * log_n[:M_sum])
    S2 = np.dot(np.conj(a_arr[:M_sum]), powers2)
    
    # Phase P
    gamma_s = mpmath.gamma(mpmath.mpc(0.5, t))
    gamma_1ms = mpmath.gamma(mpmath.mpc(0.5, -t))
    cond = mpmath.mpf(N) / (4 * mpmath.pi**2)
    cond_factor = mpmath.power(cond, mpmath.mpc(0, t))
    P_mp = gamma_1ms / gamma_s * cond_factor
    P = complex(float(P_mp.real), float(P_mp.imag))
    
    return S1, S2, P

buhler_zeros = [5.1015, 5.5613, 6.0244, 6.4910, 6.9613]

# Sweep over all root numbers d in range(20)
# Since the character has order 10, the root number w should be in Q(zeta_20).
print("\nSweeping root number exponents d in range(20) for w = zeta_20^d:")
for d in range(20):
    w0 = zeta20 ** d
    # Root numbers for the conjugate forms are w^(j) = sigma_j(w0)
    w_conjs = [zeta20 ** ((d * gal_m[j]) % 20) for j in range(4)]
    
    # Evaluate at the 5 Buhler zeros
    vals = []
    for t in buhler_zeros:
        # Check all 4 forms and see the minimum L-value
        min_L = 999.0
        best_j = -1
        for j in range(4):
            S1, S2, P = compute_S1_S2_P(t, j)
            L = S1 + w_conjs[j] * P * S2
            if abs(L) < min_L:
                min_L = abs(L)
                best_j = j
        vals.append((best_j, min_L))
        
    avg_min = np.mean([v[1] for v in vals])
    max_min = np.max([v[1] for v in vals])
    if max_min < 0.05:
        print(f"\n*** FOUND CONSISTENT ROOT NUMBER Exponent d = {d} (w0 = {w0:.4f}) ***")
        for idx, t in enumerate(buhler_zeros):
            j, val = vals[idx]
            print(f"  t={t}: best form j={j} (m={gal_m[j]}), |L|={val:.6f}, w={w_conjs[j]:.4f}")
        break
    else:
        print(f"  d={d:2d}: max_min={max_min:.4f}, avg_min={avg_min:.4f}, best_forms={[v[0] for v in vals]}")
