import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.NumberTheory.LegendreSymbol.AddCharacter
import Mathlib.Analysis.SpecialFunctions.Pow.Real

/-!
# Discrete Fourier Transform on Finite Cyclic Groups

This file formalizes the Discrete Fourier Transform (DFT) matrix over the cyclic group `ZMod N`
with values in `ℂ`, proving that it is unitary with explicit conjugate-transpose inverse.

## Main Definitions
- `zmodChar_C N zeta hzeta`: The canonical additive character on `ZMod N` generated by
  a primitive root of unity `zeta`.
- `dftMatrix zeta hzeta`: The `N × N` normalized DFT matrix with entries
  `dftMatrix i j = (1 / √N) * χ(i * j)`.
- `dftMatrix_star zeta hzeta`: The conjugate transpose of `dftMatrix`.

## Main Results
- `dft_mul_star`: The DFT matrix satisfies `dftMatrix * dftMatrix_star = 1`.
- `dft_star_mul`: The conjugate transpose satisfies `dftMatrix_star * dftMatrix = 1`.

## Tags
dft, discrete fourier transform, additive character, unitary matrix
-/

open Matrix Finset Complex

variable {N : ℕ+} (zeta : ℂ) (hzeta : IsPrimitiveRoot zeta N)

/-- The additive character on `ZMod N` induced by the primitive root `zeta`. -/
noncomputable def zmodChar_C : AddChar (ZMod N) ℂ := 
  AddChar.zmodChar N hzeta.pow_eq_one

/-- Evaluation of the character on negated argument equals the multiplicative inverse. -/
lemma char_neg (x : ZMod N) : (zmodChar_C zeta hzeta) (-x) = ((zmodChar_C zeta hzeta) x)⁻¹ := 
  eq_inv_of_mul_eq_one_left <| by rw [← AddChar.map_add_mul, add_left_neg, AddChar.map_zero_one]

/-- Complex conjugation of the character equals evaluation on the negated argument. -/
lemma char_star (x : ZMod N) : star (zmodChar_C zeta hzeta x) = zmodChar_C zeta hzeta (-x) := by
  have h_norm : ‖zmodChar_C zeta hzeta x‖ = 1 := by
    change ‖AddChar.zmodChar N _ x‖ = 1
    rw [AddChar.zmodChar_apply, norm_pow, Complex.norm_eq_one_of_pow_eq_one hzeta.pow_eq_one N.ne_zero, one_pow]
  rw [char_neg]
  apply eq_inv_of_mul_eq_one_left
  have hz2 := RCLike.conj_mul (zmodChar_C zeta hzeta x)
  rw [← RCLike.star_def] at hz2
  exact hz2.trans (by simp [h_norm])

/-- The normalized Discrete Fourier Transform Matrix on `ZMod N`. -/
noncomputable def dftMatrix : Matrix (ZMod N) (ZMod N) ℂ :=
  fun i j ↦ (1 / Real.sqrt N) * zmodChar_C zeta hzeta (i * j)

/-- Conjugate transpose of the DFT Matrix. -/
noncomputable def dftMatrix_star : Matrix (ZMod N) (ZMod N) ℂ :=
  fun i j ↦ star (dftMatrix zeta hzeta j i)

/-- The DFT matrix is unitary: `F * Fᴴ = I`. -/
lemma dft_mul_star :
    dftMatrix zeta hzeta * dftMatrix_star zeta hzeta = 1 := by
  ext i j
  simp only [mul_apply, one_apply, dftMatrix, dftMatrix_star]
  have hs : star (1 / (Real.sqrt N : ℂ)) = 1 / (Real.sqrt N : ℂ) := by
    simp only [star_div', star_one, RCLike.star_def, conj_ofReal]
  have hs2 : (Real.sqrt N : ℂ) ^ 2 = (N : ℂ) := by norm_cast; exact Real.sq_sqrt (by positivity)
  have hN : (N : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr N.ne_zero
  have h_sum_congr : (∑ k : ZMod N, (1 / (Real.sqrt N : ℂ) * zmodChar_C zeta hzeta (i * k)) * star (1 / (Real.sqrt N : ℂ) * zmodChar_C zeta hzeta (j * k))) =
    ∑ k : ZMod N, (1 / (N : ℂ)) * zmodChar_C zeta hzeta ((i - j) * k) := by
    apply sum_congr rfl
    intro k _
    rw [star_mul', char_star, hs]
    calc
      _ = (1 / (Real.sqrt N : ℂ) ^ 2) * (zmodChar_C zeta hzeta (i * k) * zmodChar_C zeta hzeta (-(j * k))) := by ring
      _ = (1 / (N : ℂ)) * zmodChar_C zeta hzeta ((i - j) * k) := by rw [hs2, ← AddChar.map_add_mul]; congr 2; ring
  rw [h_sum_congr, ← Finset.mul_sum]
  have h_sum_comm : (∑ i_1 : ZMod N, (zmodChar_C zeta hzeta) ((i - j) * i_1)) = ∑ i_1 : ZMod N, (AddChar.zmodChar N hzeta.pow_eq_one) (i_1 * (i - j)) := by
    apply sum_congr rfl; intro k _; exact congrArg _ (mul_comm _ _)
  rw [h_sum_comm, AddChar.sum_mulShift _ (AddChar.zmodChar_primitive_of_primitive_root N hzeta)]
  simp_rw [sub_eq_zero]
  split_ifs with h_eq
  · rw [ZMod.card, one_div, inv_mul_cancel hN]
  · simp

/-- The DFT matrix is unitary: `Fᴴ * F = I`. -/
lemma dft_star_mul :
    dftMatrix_star zeta hzeta * dftMatrix zeta hzeta = 1 := by
  ext i j
  simp only [mul_apply, one_apply, dftMatrix, dftMatrix_star]
  have hs : star (1 / (Real.sqrt N : ℂ)) = 1 / (Real.sqrt N : ℂ) := by
    simp only [star_div', star_one, RCLike.star_def, conj_ofReal]
  have hs2 : (Real.sqrt N : ℂ) ^ 2 = (N : ℂ) := by norm_cast; exact Real.sq_sqrt (by positivity)
  have hN : (N : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr N.ne_zero
  have h_sum_congr : (∑ k : ZMod N, star (1 / (Real.sqrt N : ℂ) * zmodChar_C zeta hzeta (k * i)) * (1 / (Real.sqrt N : ℂ) * zmodChar_C zeta hzeta (k * j))) =
    ∑ k : ZMod N, (1 / (N : ℂ)) * zmodChar_C zeta hzeta ((j - i) * k) := by
    apply sum_congr rfl
    intro k _
    rw [star_mul', char_star, hs]
    calc
      _ = (1 / (Real.sqrt N : ℂ) ^ 2) * (zmodChar_C zeta hzeta (-(k * i)) * zmodChar_C zeta hzeta (k * j)) := by ring
      _ = (1 / (N : ℂ)) * zmodChar_C zeta hzeta ((j - i) * k) := by rw [hs2, ← AddChar.map_add_mul]; congr 2; ring
  rw [h_sum_congr, ← Finset.mul_sum]
  have h_sum_comm : (∑ i_1 : ZMod N, (zmodChar_C zeta hzeta) ((j - i) * i_1)) = ∑ i_1 : ZMod N, (AddChar.zmodChar N hzeta.pow_eq_one) (i_1 * (j - i)) := by
    apply sum_congr rfl; intro k _; exact congrArg _ (mul_comm _ _)
  rw [h_sum_comm, AddChar.sum_mulShift _ (AddChar.zmodChar_primitive_of_primitive_root N hzeta)]
  have h_iff : j - i = 0 ↔ i = j := by constructor <;> intro h <;> [exact sub_eq_zero.mp h |>.symm; rw [h, sub_self]]
  simp_rw [h_iff]
  split_ifs with h_eq
  · rw [ZMod.card, one_div, inv_mul_cancel hN]
  · simp
